### PR TITLE
Multiple accounts Web login 

### PR DESCRIPTION
**Pull request by sbertix**
Rewritten `InstagramLoginWebView` to allow for multiple accounts to log in without cache and cookie conflicts #27.
I tried to keep everything as close as possible to what is used to be, while greatly reducing the amount of code, but support for **less than iOS 11** had to be dropped (I feel like it's not a big issue, though, since once can simply rely on `Siwa` instead, and iOS 10 is not that popular anymore), as well as _preloaders_, which are quite an easy addition though (and I feel like they should be left to the developers implementing the library of their own accord).

(Bonus: no more WKCookieWebView 🎉)

### CODE REVIEW

**Comment by TheM4hd1** [comment]
Thanks for this update, a lot of users using this library with iOS 10.0 and higher compatibility.
If we simply remove support for iOS 10.0 in web login, they may face a problem and needs a lot of work to handle login via `Siwa`, most people prefer to use web login instead of native login.
So I suggest to keep the older version for iOS 10.0 and add this update for iOS 11.0 and higher.

**Comment by sbertix** [comment]
I actually might have an iOS 10 compatible fix 😊
I'm working on it as soon as I have the time.

**Comment by TheM4hd1** [comment]
Sounds good, I think we should wait for this fix to merge both PR.
There is a possibility for users to update the library and causes issue for their app.
Thanks.

**Comment by sbertix** [comment]
So… apparently the version already on `master` doesn't work on `iOS 10`, because `httpOnly` cookies (specifically `session_id` in our case) are already not caught by `WKCookieWebView`, so if somebody was to actually try it on `iOS 10` the login would **always** either fail or fallback to already cached `session_id`, thus not actually changing account.
I feel like, since it doesn't work already, actually hiding the deceleration behind a `@available(iOS 11, *)` check might be a big improvement, avoiding users hours of trying to figure out why it's not working just to then find out it simply could not on their `iOS 10` device.

**Pull request merged**
