### PR TITLE
Upload function for Photo

### PR DESCRIPTION
**Pull request by TheM4hd1**
Tested it a few times and worked fine. a little messy but you can use it for now.
#206

### CODE REVIEW

**Comment by TheM4hd1** [comment]
@sbertix I see there are some `SwiftLint` issues, if you can please check them.

**Comment by sbertix** [comment]
Done 💪 
Thank you for the super quick PR.

**Comment by sbertix** [comment]
For accounts marked as spam, this triggers the "_you have shared your password with services to get likes_ […] _change your password__" challenge.\
I implemented a different method on **Swiftagram**, porting **dilame**'s, but it returns the same error. 😢
I genuinely have no idea on how to bypass it…
@TheM4hd1

**Comment by TheM4hd1** [comment]
@sbertix if you can provide me an account that marked as spam, so I can try and investigate about the issue.

**Pull request merged**
