### PR TITLE
Fix for RateLimit.DeviceRateLimit

### PR DESCRIPTION
**Pull request by TheM4hd1**
When trying to unfollow/follow people, you may face an error, here is the description of error:
```
  "category" : "instagram_unfollow",
  "feedbackAction" : "report_problem",
  "feedbackAppealLabel" : "Tell us",
  "feedbackIgnoreLabel" : "OK",
  "feedbackMessage" : "We limit how often you can do certain things on Instagram, like unfollowing people, to protect our community. Tell us if you think we made a mistake.",
  "feedbackTitle" : "Try Again Later",
  "feedbackUrl" : "repute\/report_problem\/instagram_unfollow\/?violation_type&responsible_policy=Ig.Policy.Engagement.DeviceRateLimit.DeviceRateLimit",
  "message" : "feedback_required",
  "spam" : true,
  "status" : "fail"
```
### How to fix?
Using a unique `device_id` can fix this problem, so I've overridden the default value of `device_id` and `phone_id` with a unique `UDID`

### CODE REVIEW

**Comment by TheM4hd1** [comment]
@mycroftcanner 
We were using a predefined `UDID` for `phoneGuid` and `deviceGuid`, so I believe those predefined `UDIDs` were marked as spam or since they're using in almost every app (even in old php, python, nodejs versions) they reach the limit faster. so using a unique `UDID` can fix this issue.
However if the account reaches maximum daily (max total requests), this error may occurs again.

**Comment by sbertix** [comment]
This won't actually fix the problem, regardless of the way **SwiftyInsta** is implemented, and it makes things worse as, as the random UUID are not implemented as argument defaults but hardcoded in the method, people wanting to pass their own are stuck with a new one every time. 
As **SwiftyInsta** still relies on "one user agent for all" (in newer version a default iOS app one), non-matching devices will always be marked as spam (and all `Device`s in the project are Android ones).

**Comment by TheM4hd1** [comment]
@sbertix if you check the commits you see that I did it exactly as you said: 

> (but this is an easy fix, just do phone_guid: UUID = .init() in the definition, and update the implementation accordingly).

I almost removed all dependencies which relates requests to device. so no device information sends from library to Instagram, I've checked their latest version and they only send a few small data on upload functions, however the endpoints works fine without them.

**Comment by sbertix** [comment]
Nope @TheM4hd1. Your implementation here is like this:

```swift
init(phone_guid: UUID) {
   self.phone_guid = .init()
}
```

The correct implementation, like I mentioned in the comment is:

```swift
init(phone_guid: UUID = .init()) {
   self.phone_guid = .init()
}
```

And updating all static devices accordingly. 

You did good in removing devices references, like I said: user agents are what matter here. That's why this is not a real fix, cause the user agent mismatch will still cause the same exact error. 
You need to rethink the single user agent approach. @TheM4hd1

**Pull request merged**
