### PR TITLE
Fix `TrayElement.coverMedia` always returns nil 

### PR DESCRIPTION
**Pull request by bariscck**
`TrayElement.coverMedia` is trying to parse `Media` object but returned response actually not a `Media` object. 

Is part of `highlights`.

returned response is;

``` 
"cover_media" : {
        "crop_rect" : [
          0,
          0.21875,
          1,
          0.78125
        ],
        "media_id" : "2238706.....",
        "cropped_image_version" : {
          "width" : 150,
          "url" : "https:\/\/instagram.fada1-2.fna.fbcdn.net.....",
          "height" : 150
        }
      }
```

### CODE REVIEW

**Comment by sbertix** [comment]
💪 

Just for future reference, but it's definitely not a big deal so don't worry. We're following default guidelines for commit naming, so imperative verbs should be preferred to past simple ones.
e.g. _Added `Cover` and `TrayElement` updated_ becomes _**Add `Cover` and update `TrayElement`**_.

**Comment by bariscck** [comment]
@sbertix I was undecided with the commit name 😊I'll follow this guidelines.

**Comment by sbertix** [comment]
No probs man. And thanx again for contributing 💪

**Comment by bariscck** [comment]
@sbertix can you create a new release for `2.3.2`?

**Comment by sbertix** [comment]
I completely forgot 😱
I'm doing it rn. Sorry man

**Comment by bariscck** [comment]
Its ok, I just wanted to remind you 😊Thanks.

**Pull request merged**
