### PR TITLE
Refactor `Model*`s and other improvements

### LINKED ISSUE #69: Rewriting `*Model`s
As suggested in #50, we should start considering a better approach for models, in time for `2.0`
Right now they directly represent the parsed JSON response, which is especially uncomfortable when dealing with media and users (and all their different definitions inside the library).

I'm proposing the following, as an improvement of the current situation. 
Any model should conform to `ParsedResponse` defined as following:
```swift
public protocol ParsedResponse {
  associatedtype RawResponse: Codable
  var rawResponse: RawResponse { get }
}
```

Where `RawResponse` might just as well represent the current models (or even a `Dictionary` tbh..., idk). 
I would not enforce `Codable` on `ParsedResponse` but maybe add an `init` with the associated `RawResponse` as an argument, but I'm open to suggestions.

Every "parsed" attribute can therefore be achieved through **accessories** of the `ParsedResponse`, either as run-time read-only `get` `var`s or `let` constants computed on `init` (depending on their computational difficulty). 
(bonus: No more `UserModel`, `CurrentUserModel`, `UserShortModel`, etc.)

Suggestions? Opinions?
I might start working on this tomorrow.

### PR DESCRIPTION
**Pull request by sbertix**
Closes #69 

### `Model*`s
- added a `DynamicResponse` holding reference to every single property of the `JSON` response (even future ones)
- added a `ParsedResponse` and `IdentifiableParsedResponse` protocols
  - use `Identifier<Element>` for implementing both/either an **integer** `primaryKey` and/or a **string** `identifier`
  - `Codable`
  - custom accessories to quickly obtain most common `DynamicResponse` "properties"

### `Device` + `UserAgent` + `ResponseMessageModel` + …
- rewritten `Device` from the start to make it more _swift-y_:
  - call `AnyDevice.random()` for a randomly generated one
  - call **brand-specific** types, e.g. `Samsung.galaxyS6` or `Samsung.random()`
  - `SessionCache`s from this commit are not compatible with previous ones

### Misc.
- rewritten `Extensions.swift`
- removed unused declarations
- better `Error` handling:
  - `CustomErrors` and `AuthenticationError` are refactored to `GenericError` and `AuthenticationError`, both actually conforming to `LocalizedError`
  - `URLs.*` now, again, throws an `Error` (`GenericError.invalidUrl` specifically) instead of calling `fatalError`
- removed imported files from external libraries
  - `keychain-swift` is now a `CocoaPods` dependency
  - `CryptoSwift` is now a `CocoaPods` dependency

## TODO
- ~rewrite all `Model`s~
- rewrite all methods still using legacy `Model`s (e.g. the pre-iOS 13 POST ones)

### CODE REVIEW

**Comment by TheM4hd1** [comment]
you should consider that sometimes the `pk` is `string`
It happened a few times for me, can't remember which endpoints, but we should handle it to prevent crashing.

**Comment by sbertix** [comment]
> you should consider that sometimes the `pk` is `string`
> It happened a few times for me, can't remember which endpoints, but we should handle it to prevent crashing.

For sure. I wasn't intending `primaryKey` = _parsed as an `Int`_. Just that, `pk`s are always representing _long integers_, even when they're returned as `String`. And `identifier`s (i.e. `mediaId`) are always intended to be `String`s.
So I'm still going to `try?` for both `String.self` and `Int.self` when decoding `.pk`, don't worry @TheM4hd1  😊

**Comment by sbertix** [comment]
Up until now all dependencies (except for `GzipSwift`) have been imported directly into the library, which makes everything pretty unreliable, and it's completely undocumented (I'm talking about the `CommonCrypto` and the `KeychainSwift` stuff).
Since we're now forcing the user to use `CocoaPods` (maybe we should working on supporting `Carthage` or even the `Swift Package Manager` for `2.0` as well), I've added `CryptoSwift` and `keychain-swift` as `CocoaPods` dependencies, instead of loose files, like they used to and added them in the `README` for attribution.
I think it makes everything easier to maintain and also clearer to end users, and I truly believe that as much as you hate external dependencies, this time is for the best 😊 
What do you think?
@TheM4hd1

**Comment by TheM4hd1** [comment]
That's right, because we are forcing to use `CocoaPods` we should move `keychain` and `crypto` as external dependencies, it makes much more sense.
and about supporting other dependency managers, Personally I'm not a fan of `Carthage` or `SPM`, in my opinion `Cocoapods` is enough.

**Comment by sbertix** [comment]
I don't like them either, personally, but I feel like if it's not too much work we could try and implement it nonetheless: more options for people to actually use the library.
At last the `Swift Package Manager`, which is **soooo much better** in `Xcode 11`.
It's surely not a priority though, imho.

**Comment by sbertix** [comment]
I've updated most models.

Some methods (e.g. all the former `.post`-only ones) still retain the old ones, but I would like to hear your feedback with all the new `DynamicResponse` mechanism 😊 @TheM4hd1 

Basically, the user can still read the entire response (_entire_ meaning **entire**,  even properties we didn't know existed, or that might exist in the future), but some common properties have useful accessories.

**Comment by TheM4hd1** [comment]
Mind-blowing update !!, it's much more better than older models but complex.
Can you describe about these new models, how they works, decoding and ...
for the ones (even me) who used old models this a huge step. I think that would be nice if you add a description about it, the use case and .. anything about these new models.
Crazy Update !! :D

**Comment by sbertix** [comment]
I will update the documentation as soon as I'm done with everything 😊 
Glad you like it man 💪

**Comment by sbertix** [comment]
Sure 😊

**Comment by sbertix** [comment]
All done 💪 (Travis should be fine rn)

**Pull request merged**
