### PR TITLE
Update to `2.2`

### LINKED ISSUE #119: Media Upload Failed with Status Code 500
Sometimes Media Upload function failed with response : 

```
<NSHTTPURLResponse: 0x281fa01a0> { URL: https://i.instagram.com/api/v1/media/configure/ } { Status Code: 500, Headers {
    "Cache-Control" =     (
        "private, no-cache, no-store, must-revalidate"
    );
    "Content-Language" =     (
        en
    );
    "Content-Length" =     (
        54
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Sun, 27 Oct 2019 20:33:36 GMT"
    );
    Expires =     (
        "Sat, 01 Jan 2000 00:00:00 GMT"
    );
    Pragma =     (
        "no-cache"
    );
    "Set-Cookie" =     (
        "csrftoken=Oigux4dghhFezUy4j20AT7Xvm9cpKZKn; Domain=.instagram.com; expires=Sun, 25-Oct-2020 20:33:36 GMT; Max-Age=31449600; Path=/; Secure",
        "rur=FRC; Domain=.instagram.com; HttpOnly; Path=/; Secure",
        "urlgen=\"{\\\"58.65.212.48\\\": 9541}:1iOpEG:KEKssAYLJRYot0JG_CwbWFLnHEk\"; Domain=.instagram.com; HttpOnly; Path=/; Secure"
    );
    "Strict-Transport-Security" =     (
        "max-age=31536000"
    );
    Vary =     (
        "Accept-Language, Cookie"
    );
    "access-control-expose-headers" =     (
        "X-IG-Set-WWW-Claim"
    );
    "content-security-policy" =     (
        "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests"
    );
    "x-aed" =     (
        11
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-fb-trip-id" =     (
        1679558926
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-xss-protection" =     (
        0
    );
} }
```

My Code: 
```swift
let picture = Upload.Picture(image: image, caption: caption, size: image.size)
        guard let handler = apiHandler else {
            completion(false)
            return
        }
        handler.media.upload(photo: picture) { (result) in
            switch result {
            case .success ( _):
                completion(true)
            case .failure(let error):
                completion(false)
            }
        }
```

### PR DESCRIPTION
**Pull request by sbertix**
In an effort to make everything _Swift_-ier, I'm proposing some changes to things that were left unchanged from `1.*`.

The new `Endpoints` implementation, other than providing a clearer insight in what's actually going on, allows for both a better imperative and declarative approach. Having a concrete reference to what the user is looking for means we could be able to move the entire `APIHandler` to an `NSOperationQueue`-like stack (should we decide to, it's just an example) or even bypass it completely (e.g. `endpoint.call()` using `Combine` or `RxSwift` for instance).
Definitely something to discuss for a possible `3.0`, since it would mean breaking everything again, more likely than not.

## What's new
- `Endpoint`: no more `URLs`, `static let`s and `func`s, just `enum`s (conforming to an `EndpointRepresentable` protocol), accepting specific arguments (when needed) — I would have loved using `5.1` new syntax, but `5.0` should do for now hahaha — **100% not final**, it might change again (for instance holding reference to the _response type_)
- `HTTPHelper` and `PaginationHelper` now accept `Endpoint`s directly (might change their name into something more _swift_y too)
- `ParsedResponse` `init(rawResponse:)` is now `init?(rawResponse:)`, automatically dealing with `rawResponse == .none` (additional checks could be easily implemented too)
- `authenticate(.user(/* some Credentials */))` is working again
- endpoints improvements and fixes
- fix #119 
- more

### CODE REVIEW

**Comment by TheM4hd1** [comment]
a few endpoints using `/v2` api
for example: 
https://github.com/TheM4hd1/SwiftyInsta/blob/bfa94f4df3359b8ed2a217cf7a7a8e9c7be2a598/SwiftyInsta/API/Constants/URLs.swift#L641
otherwise they won't work.

**Comment by sbertix** [comment]
Thanks for pointing it out :muscle:
I'll fix it in time for the final commit.

**Comment by TheM4hd1** [comment]
`Endpoints` returns wrong values for URLs
I applied the fixed for `Credentials` on current stable version and it worked fine.
please re-check the `Endpoints`

**Comment by sbertix** [comment]
I've changed the all `Endpoint`s thing again.  
It's definitely easier to read, while being a bit more complex implementation-wise.

Do you mind checking if it fixes anything or if I messed up the actual endpoint paths? @TheM4hd1 

Still can't test it myself unfortunately 😔

**Comment by TheM4hd1** [comment]
@sbertix will check soon

**Comment by sbertix** [comment]
Done @TheM4hd1 💪

**Pull request merged**
