### PR TITLE
Instance independency + `SessionCache` persistance

### PR DESCRIPTION
**Pull request by sbertix**
This is intended as a base for `2.0`, to be pushed to the `development` branch.
Refer to **#50** for feedback, suggesting changes, or discussing features, because this is just a **"draft"**: you're all more than welcome to partecipate and change it.

DONE: 
- `APIHandler` no longer uses _singletons_: multiple instances, logged with multiple accounts, work as intended
- streamlined login experience
- dropped support for `username` + `password` out of the box: use `Siwa` instead (maybe merging the two projects?)
- no more redundant `protocol`s and related _conformances_
- `Swift`ified definitions
- added caching options for `Login.Response` (`persist()`), and the ability to retrieve the related `SessionCache` to streamline the login process (`SessionCache.persisted(with:)`) **[requires the `Security` framework to be added to the pod dependencies (?)]** — `1.*` `SessionCache`s are not compatible (maybe a name change to avoid confusion might help)
- _request specific_ `delay`, and limited the _default_ one to a `Double` closed range between `1` and `2` seconds
- authentication data (i.e. _cookies_ and related properties) is now marked as `internal` as an incentive not to abuse it
- added `GzipSwift` `pod` dependency to try and fix (?) #39 (`/feed/timeline` now requires `.gzip` data)
- minor improvements and bugfixes

TODO:
- add back _Tests_
- bring support for these changes to `Siwa`, which is incompatible right now
- actually fixing #39 
- ~caching options for (the new) `SessionCache`~

### CODE REVIEW

**Comment by sbertix** [comment]
As always I forgot to change the reference to the new files path hahaha… 🙈 
Do you mind changing it when/if you push it? 
Thanks. Sorry @TheM4hd1

**Comment by TheM4hd1** [comment]
@sbertix Sure I will fix the references to new files.
It takes a few days for me to check the PR, a little busy these days but I try to finish it by this weekend.
Regards.

**Comment by sbertix** [comment]
Am I earning the _Collaborator_ "badge"? Hahahaha 🙈 @TheM4hd1

**Comment by TheM4hd1** [comment]
Contact me by email please.

**Pull request merged**
