### PR TITLE
Merging `Siwa` with `SwiftyInsta`

### LINKED ISSUE #57: Merging `Siwa` into `SwiftyInsta`
**[DONE IN `SwiftyInsta` v. `2.0`]**

The login mechanics used in [Siwa](https://github.com/TheM4hd1/Siwa) are far superior to the ones in `SwiftyInsta`, yet `SwiftyInsta` still provides a way for headless login, only resulting in code duplication.

Instead of dropping support for authentication through _username_ and _password_ from `SwiftyInsta` (like I proposed in my draft for `2.0` now in the `development` branch), why not adding all of `Siwa` functionalities back to `SwiftyInsta`?

What's the reasoning behind having them as separate frameworks?

### PR DESCRIPTION
**Pull request by sbertix**
The objective here is to provide the entire functionality of the `Siwa` library directly inside `SwiftyInsta`, while greatly simplifying it.
It closes #57.

## Authentication
```swift
// these need to be strong references.
self.credentials = Credentials(username: /* username */, password: /* password */, verifyBy: .text)
self.handler = APIHandler()
handler.authenticate(with: .credentials(credentials)) {
	switch $0 {
	case .success(_, _): /* persist as usual */
	case .failure(let error):
		if error.requiresInstagramCode {
			/* update interface to ask for code */
		} else {
			/* notify the user */
		}
	}
}
```

Once the user has typed the two factor authentication code or challenge code, you simply do
```swift
self.credentials.code = /* the code */
```
And the `completionHandler` in the previous `authenticate(with: completionHandler:)` will automatically catch the response.
All the calls to ask for code, send code, etc. you're used to in `Siwa` are now taken care of for you under the hood.

### CODE REVIEW

**Comment by TheM4hd1** [comment]
if the challenge code required happens, we can simply call this function to show email or sms hint values to user.

```swift
webHandler.getChallengeInfo { (resForm) in
    if let field = resForm?.entryData?.Challenge?.first?.extraData?.content?.last?.fields?.first {
        if field.values?.count == 2 {
            guard let first = field.values?.first else { return }
            guard let last = field.values?.last else { return }
            guard let firstValue = first.value else { return }
            
            if firstValue == 1 {
                // first.label is Email ma****@g**.com
                // last.label is Phone: 09*****76
            } else {
                // first.label and last.label are only Email: ma****@g**.com
            }
        }
    }
}
```

**Comment by sbertix** [comment]
Thins is… I don't feel like adding a method specific to just one case of `Login.Request` makes much sense.
But every time a challenge occurs I pass to the `completionHandler` a custom `AuthenticationError` saying whether it's a `checkpoint`, a `checkpointLoop`, a `twoFactor`. I feel like it'd make more sense to do sth like…

```swift
public enum AuthenticationError: Error, LocalizedError {
	// ...
	case checkpoint(suggestion: String)
	case twoFactor(suggestion: String)
}
```
… instead of duplicating code for a single `case` of authentication in the `APIHandler`.
What do you think?

**Comment by TheM4hd1** [comment]
I think it can be a good feature, even if it's for a single case of login.
It help developers to make more exciting UI if the suggestions displays to user. exactly like the way Instagram doing this.
I think we should cover all available helpful features.

**Comment by sbertix** [comment]
I've added it! 💪
The login flow it's not working, but the `suggestion` value is there!

**Comment by sbertix** [comment]
It's all working as it should now, and I've also updated the `README.md` with the example above.
I thought it was gonna take way longer, but you truly did an amazing job with `Siwa` and it was super smooth to replicate and adjust 💪 @TheM4hd1

**Comment by TheM4hd1** [comment]
Thanks for your job @sbertix 
PR Approved.

**Pull request merged**
