### PR TITLE
Fix friendship status

### LINKED ISSUE #107: Friendship status is not working
Today i realized that friendshipStatus is not working **anymore** with the `Invalid response. 405` error code.

Reason for that might be `.get .post` methods. Because there are 2 types of getFriendshipstatus code one using `.get` and other (_which is commented not used at the moment_) using `.post`.

### PR DESCRIPTION
**Pull request by sbertix**
Closes #107.

I didn't have a chance to actually try it, but it should work.
Let me know @TheM4hd1 😊

### CODE REVIEW

**Comment by anonrig** [comment]
I'm receiving `error custom("No response.")`

**Comment by sbertix** [comment]
My bad. I didn't change the body parameter to make it work @anonrig 
Let me know if it does now cause I can't test it.

**Comment by anonrig** [comment]
I'm receiving the same error again but it might be the pod cache, do you know how to invalidate it?

**Comment by sbertix** [comment]
I feel like switching back to `master` and then to `sb/bugixes` again might fix every cash related issue when trying `pod update` @anonrig

**Pull request merged**
