### PR TITLE
Add custom user agent support for `LoginWebView`

### PR DESCRIPTION
**Pull request by sbertix**
Amend #156.
Revert #157.

### CODE REVIEW

**Comment by sbertix** [comment]
Any update? @TheM4hd1 😊

**Comment by sbertix** [comment]
It did not save the user agent setup on the `LoginWebView` 😢 
It's not gonna work either. I don't know what happened.

**Comment by TheM4hd1** [comment]
idk why travis doesn't work anymore on pull requests.
the build failed again on travis. weird.

**Comment by sbertix** [comment]
I've fixed everything, bumped CocoaPods version and added the tag. @TheM4hd1

**Pull request merged**
